development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:d7e9288fe1160e75ed45860b0ff11307@jack.redistogo.com:10259/
  channel_prefix: medico_production
